### ISSUE TITLE
Wrong URL in the showAsLink method

### ISSUE THREAD

**Issue by phuclh** [koss-shtukert/laravel-nova-select2-auto-complete#10]
The correct URL is: `/nova/resources/product-categories/7` but it generated to `/nova/resources/productcategories/7`.

Thank you!!!

**Comment by DmitrySur** [comment]
Try it - #6

**Comment by koss-shtukert** [comment]
Fixed on ([Release v1.6](https://github.com/koss-shtukert/laravel-nova-select2-auto-complete/releases/tag/v1.6))
