### ISSUE TITLE
Why adding Google Analytics

### ISSUE THREAD

**Issue by ahmedkandel** [koss-shtukert/laravel-nova-select2-auto-complete#18]
Hi,

I was updating the packages then found that the new version has a breaking change in namespace from 'Koss' to 'KossShtukert' which is ok but it also has google analytics 'UA-142757326-1' can you please explain this.

Thanks.

**Comment by koss-shtukert** [comment]
Hi @ahmedkandel, yes I'm setup GA for my component. It's only for monitoring real using. In the [latest version](https://github.com/koss-shtukert/laravel-nova-select2-auto-complete/releases/tag/v1.13), I added a possibility to disable GA. Please see [this section](https://github.com/koss-shtukert/laravel-nova-select2-auto-complete#google-analytics)

**Comment by yehudahkay** [comment]
I believe you should remove this

**Comment by koss-shtukert** [comment]
Ok, in next release (v1.17) I'll remove GA
