### ISSUE TITLE
Validation issue (not required field making a red background when required field is validating)

### ISSUE THREAD

**Issue by cnraju** [koss-shtukert/laravel-nova-select2-auto-complete#2]
` Select2::make('Title')
                    ->rules('required')
                    ->options($this->get_titles())
                    ->configuration([
                        'placeholder' => __('Select a title'),
                        'allowClear' => true,
                        'minimumResultsForSearch' => 1
                    ]),`

    Select2::make('Book Preference', 'book_preference')
                    ->hideFromIndex()
                    ->options(['Regular' => 'Regular', 'Deluxe' => 'Deluxe'])
                    ->configuration([
                        'placeholder' => __('Select Preference'),
                        'allowClear' => true,
                        'minimumResultsForSearch' => 1
                    ]),

When submititng form both fields background becomes red

**Comment by koss-shtukert** [comment]
Fixed in [Release v1.4 (Fixed bugs)](https://github.com/koss-shtukert/laravel-nova-select2-auto-complete/releases/tag/v1.4)
