### ISSUE TITLE
Change in package name breaks composer update

### ISSUE THREAD

**Issue by yehudahkay** [koss-shtukert/laravel-nova-select2-auto-complete#22]
Hi thanks for the latest updates, upon running composer update resource broke as needed 

use KossShtukert\LaravelNovaSelect2\Select2;

instead of 

use Koss\LaravelNovaSelect2\Select2;

If this change was necessary perhaps you should mark it as not compatible with previous version

**Comment by koss-shtukert** [comment]
@yehudahkay 
Thank you.
Marked v1.13 as not compatible with the previous version
