### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by cnraju** [koss-shtukert/laravel-nova-select2-auto-complete#3]
During updating record, my select2 field which is required is selected. But if another required field is empty then select2 field also making the red background. And sometimes there is two input box for one select2.
![validatin](https://user-images.githubusercontent.com/45790226/50585689-3ea1f800-0e9c-11e9-9271-8f13dd9bc3d8.jpg)

In above picture Select preference is not required but still making red background. And see title and country fields also making red background (they are already selected) and showing two times .

**Comment by koss-shtukert** [comment]
Duplicate https://github.com/koss-shtukert/laravel-nova-select2-auto-complete/issues/2
