### ISSUE TITLE
Set default value?

### ISSUE THREAD

**Issue by yehudahkay** [koss-shtukert/laravel-nova-select2-auto-complete#30]
Hi and thank you!

Is there any way to pass a value to the select2 when creating it which will be the default value?

**Comment by koss-shtukert** [comment]
Hi @yehudahkay, right now you could not  pass the default value, but in next release, I've added this possibility

**Comment by yehudahkay** [comment]
Thank you! Is it released?

**Comment by koss-shtukert** [comment]
@yehudahkay, not now, in Release v1.16 will be added and I've updated the documentation

**Comment by yehudahkay** [comment]
Wow thank you, ive seen some repositories which have releases on github and then you can subscribe to them

**Comment by koss-shtukert** [comment]
@yehudahkay already in [Release v1.16](https://github.com/koss-shtukert/laravel-nova-select2-auto-complete/releases/tag/v1.16)
