### ISSUE TITLE
Select2 tree support

### ISSUE THREAD

**Issue by angauber** [koss-shtukert/laravel-nova-select2-auto-complete#33]
I will like to use your package to implement a tree, is this something planned ?
For now I'm dooing it like so:

            Select2::make(trans('session.label'), 'session_id')
                ->default(2)
                ->configuration([
                    'placeholder' => __('Choose options'),
                    'allowClear' => true,
                    'minimumResultsForSearch' => 1,
                    'multiple' => false,
                ])
                ->withMeta([
                    'options' => [
                        [
                            'text' => 'groupe 1',
                            'children' => [
                                [
                                     'id' => 1,
                                     'text' => 'groupe 1.1',
                                ],
                                [
                                     'id' => 2,
                                     'text' => 'groupe 1.2',
                                ],
                                ...
                            ]
                        ],
                    ],
                ]),
Evrything works fine but for some reason setting the default value does not work, the change is not triggered by vue.js

Do you have any idea on how I could fix this without having to touch at your package ?

Possible fix:

change `resources/js/FormField`

                // This is necessary to get a multiselect to show its selected values on initialization
                if (this.options.multiple) {
                    select2.val(this.value).trigger('change');
                }
To

            // This is necessary to get a multiselect or a tree to show its selected values on initialization
            if (this.options.multiple || this.options.tree) {
                select2.val(this.value).trigger('change');
            }

**Comment by koss-shtukert** [comment]
@angauber 
Done in [Release v1.18](https://github.com/koss-shtukert/laravel-nova-select2-auto-complete/releases/tag/v1.18)

**Comment by koss-shtukert** [comment]
@angauber I'm close the issue.
If you have any question do not hesitate
