### ISSUE TITLE
OptGroup support ?

### ISSUE THREAD

**Issue by ghost** [koss-shtukert/laravel-nova-select2-auto-complete#34]
Hi!
is package support <optgroup>'s ?

If no - im requesting this support.

**Comment by ghost** [comment]
ill try to modify options method.

https://github.com/koss-shtukert/laravel-nova-select2-auto-complete/pull/35

**Comment by koss-shtukert** [comment]
@h-zone 
Done in [Release v1.18](https://github.com/koss-shtukert/laravel-nova-select2-auto-complete/releases/tag/v1.18)
