### ISSUE TITLE
Unable to multiselect

### ISSUE THREAD

**Issue by neppoz** [koss-shtukert/laravel-nova-select2-auto-complete#37]
Hello,

could you help me out with this one? I am trying to use the multiselect. I get the following error and can't figure it out:

> Call to undefined method App\Nova\Channel::all()

Here are my realtionships

> /**
>      * Relationship to channels.
>      *
>      * @var array
>      */
>     public function channels()
>     {
>         return $this->belongsToMany(Channel::class);
>     }
> 
>     /** get the channel items */
>     public function getChannelsAttribute()
>     {
>         return $this->channels->pluck('id', 'name')->all();
>     }
> 
>     public function setChannelsAttribute($value)
>     {
>         $channels = explode(",", $value);
>         $this->channels()->sync($channels);
>     }

And on my resource it stops on this line:

>  $channels = Channel::all()->pluck('channel', 'id');

The database has a table with the following columns:

> id, channel, from

**Comment by neppoz** [comment]
Got it, i forgot to include the the model. Now i have a new problem. The values are set in the table, but the accessor does not fire.

**Comment by koss-shtukert** [comment]
@neppoz what you mean, "accessor doesn't fire"?

**Comment by neppoz** [comment]
Hello, i figured it out. It was a problem with the relationship itself. Sorry, everything is fine.
