### ISSUE TITLE
showAsLink() links to wrong resource

### ISSUE THREAD

**Issue by MitchellMcKenna** [koss-shtukert/laravel-nova-select2-auto-complete#5]
showAsLink() is linking to `/nova/resources/products/111130` where the id is correct but the resource segment of the url is wrong, it should be `/nova/resources/comments/111130`.

Is there a way for it to know which resource it should be linking to (is something set during the make() call that ->showAsLink() chains off of could use)? If not, maybe we make that an optional param you can pass to showAsLink()? eg. `->showAsLink(true, Comment::class)`

**Comment by koss-shtukert** [comment]
Extended in [Release v1.5](https://github.com/koss-shtukert/laravel-nova-select2-auto-complete/releases/tag/v1.5)

**Comment by MitchellMcKenna** [comment]
Awesome, thanks @koss-shtukert!
