### ISSUE TITLE
Wrong Url in the showAsLink () method.

### ISSUE THREAD

**Issue by DmitrySur** [koss-shtukert/laravel-nova-select2-auto-complete#6]
Hi. Faced a problem when getting the URL of the resource. Nova generates references to resources in the style of the kebab-case in the plural.
For myself, I took the following action in Select2.php:
`
        if ($resource) {
            $resource = new ReflectionClass($resource);
            $resource = (string)Str::kebab($resource->getShortName()) . 's';
        }
`
And on the detailed page the link refers to the page resource, and not to the one specified in the settings. 
I think, that problem in vue file DetailField.

**Comment by koss-shtukert** [comment]
Fixed on ([Release v1.6](https://github.com/koss-shtukert/laravel-nova-select2-auto-complete/releases/tag/v1.6))
