### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by yehudahkay** [koss-shtukert/laravel-nova-select2-auto-complete#7]
Thank you for this plugin! Using latest version following error.

If I have a validation error in the select2, then I fix it, then I have a different validation error, I get the following:

![image](https://user-images.githubusercontent.com/9964988/54191562-d7697b00-44be-11e9-8da7-e6c1463ecc67.png)

**Comment by koss-shtukert** [comment]
Fixed on ([Release v1.7 (Fixed Validation issue)](https://github.com/koss-shtukert/laravel-nova-select2-auto-complete/releases/tag/v1.7))

@yehudahkay thank for you issue!

**Comment by yehudahkay** [comment]
Thank you!
