### ISSUE TITLE
Not seeing data in index view

### ISSUE THREAD

**Issue by yehudahkay** [koss-shtukert/laravel-nova-select2-auto-complete#8]
Hi I am using the laravel 5.8 and nova 2.0 I am not seeing the data displaying in the index with this package. In the picture you can see there are no privileges, if I change to regular select I see them

![image](https://user-images.githubusercontent.com/9964988/54202940-cb3ee700-44d9-11e9-8f9f-dc5e01876b79.png)

![image](https://user-images.githubusercontent.com/9964988/54202980-ec073c80-44d9-11e9-9bb3-6423edb489a7.png)

**Comment by koss-shtukert** [comment]
Hi @yehudahkay, could you provide your code?

**Comment by yehudahkay** [comment]
Hi thank you! I'm guessing it's because of the data in my select, though it works with the default select field. The data is in the following format:

$admin_privileges = [
            '{"role":"admin"}' => 'Admin'
        ];

**Comment by koss-shtukert** [comment]
Hi, @yehudahkay the data must be in valid format.
For example:
`$categories = Category::get()->pluck('name', 'id')`
`...`
`Select2::make('Parent category', 'category_id')`
`                ->sortable()`
`                ->options($categories)`
`                ->configuration([`
`                    'placeholder'             => __('Choose an option'),`
`                    'allowClear'              => true,`
`                    'minimumResultsForSearch' => 1`
`                ])`
`                ->showAsLink()`
and after in you index view you cat see valid link to parent category resource.

If you don't wont use select2 option as link please don't use `showAsLink()` method, than you can see you option like as text

**Comment by yehudahkay** [comment]
There isn't anything wrong with that format

https://nova.laravel.com/docs/1.0/resources/fields.html#field-types

Again, this works with the nova select field type

**Comment by koss-shtukert** [comment]
Are you using `showAsLink()` method?

**Comment by yehudahkay** [comment]
No i am using displayUsingLabels()

**Comment by koss-shtukert** [comment]
Could you provide your `Select2::make()` code?

**Comment by yehudahkay** [comment]
So this should reproduce, it should work with select but not select2 in index view
```
Select::make('Privileges')
                ->options([
'{"role":"admin"}' => 'Admin'
])
                ->displayUsingLabels()
                ->sortable(),
```

**Comment by koss-shtukert** [comment]
Hi @yehudahkay , you can remove `displayUsingLabels` method, because `Select2` always show the selected result as label and update your `Select2` on latest version ([Release v1.8](https://github.com/koss-shtukert/laravel-nova-select2-auto-complete/releases/tag/v1.8))

**Comment by yehudahkay** [comment]
Thank you, I tried installing the latest v 1.10 but it isn't working for me at all

**Comment by koss-shtukert** [comment]
Could you look at console output in your browser and provide `Select2::make()` code and screens again?

**Comment by yehudahkay** [comment]
Thank you! The field doesn't appear on the screen. There is nothing in the console.  i am trying with this code

use Koss\LaravelNovaSelect2\Select2;

`Select2::make('Title')
                ->options([
                    'Mr' => 'Mr',
                    'Mrs' => 'Mrs',
                    'Ms' => 'Ms',
                    'Dr' => 'Dr',
                    'Prof' => 'Prof',
                ])
                ->configuration([
                    'placeholder'             => __('Choose an option'),
                    'allowClear'              => true,
                    'minimumResultsForSearch' => 1
                ]),`

**Comment by gustavowiller** [comment]
I had the same problem. And it works at release 1.9

**Comment by koss-shtukert** [comment]
Fixed on ([Release v1.11](https://github.com/koss-shtukert/laravel-nova-select2-auto-complete/releases/tag/v1.11))

**Comment by yehudahkay** [comment]
Great! It is working now but still the data doesn't display in index view. Here is my code:

```
Select2::make('Privileges')
                ->options([
'{"role":"admin"}' => 'Admin'
])
                ->configuration([
                    'placeholder'             => __('Choose an option'),
                    'allowClear'              => true,
                    'minimumResultsForSearch' => 1
                ])
```

**Comment by koss-shtukert** [comment]
I'm totally don't understand why it's not working for you.
This is my code, all work fine:
```
Select2::make('Description')
                ->options(['{"role":"admin"}' => 'Admin'])
                ->configuration([
                    'placeholder'             => __('Choose an option'),
                    'allowClear'              => true,
                    'minimumResultsForSearch' => 1
                ]),
```
![image](https://user-images.githubusercontent.com/709096/54993014-803ccd80-4fc9-11e9-9608-b9a7a6e6b934.png)

![image](https://user-images.githubusercontent.com/709096/54993034-8af76280-4fc9-11e9-94d2-b078135d2209.png)

![image](https://user-images.githubusercontent.com/709096/54993051-9a76ab80-4fc9-11e9-902d-e16f530b34a7.png)

Maybe some problems in you DB? Some setters before saving etc...

**Comment by yehudahkay** [comment]
Thank you for checking, if i get some time i will try to figure out the issue

**Comment by koss-shtukert** [comment]
Ok, i'm closing this issue. If your got some problem with `Select2` component please open are new issue

**Comment by yehudahkay** [comment]
I ran composer update today and later installed, it is working now, thanks!
